pipeline:
  build_docker_image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t nginx:$${DRONE_COMMIT_SHA} .

  test:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run --name docker-nginx-test -e NGINX_CONFIG_FILE=/nginx.conf -v ${PWD}/tests/nginx.conf:/nginx.conf -d nginx:$${DRONE_COMMIT_SHA}
      - apk apk upgrade --no-cache
      - apk add --no-cache curl
      - sleep 3
      - curl -s -f http://172.17.0.1:10080

  latest_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_nginx" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:latest
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/nginx:latest
      - docker push quay.io/ukhomeofficedigital/nginx:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
 
  tag_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_nginx" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/nginx:$${DRONE_TAG}
    when:
      event: tag
