pipeline:
  test:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - apk update && apk add bash curl
      - docker build -t nginx-test-img -f Dockerfile-test .
      - docker run --name nginx-test -e NGINX_CONFIG_FILE=/nginx.conf -d nginx-test-img
      - sleep 3
      - docker exec nginx-test curl -sf localhost:10080
      - ./test-clean-up.sh

  build_docker_image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t nginx:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]
      branch: master

  latest_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_nginx" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:latest
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/nginx:latest
      - docker push quay.io/ukhomeofficedigital/nginx:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
 
  tag_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_nginx" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag nginx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/nginx:$${DRONE_TAG}
    when:
      event: tag
